// Code generated by codeParser. DO NOT EDIT.
// Code generated by codeParser. DO NOT EDIT.
// Code generated by codeParser. DO NOT EDIT.

package example

import (
	"caseGenerator/utils"
	"testing"
)

func Test_requestRequestEllipsis(t *testing.T) {
	type fields struct {
	}
	type args struct {
		req2 string

		req1 []string
	}
	tests := []struct {
		args    args
		name    string
		fields  fields
		wantErr bool
	}{
		{
			name: "15902aee-f5a1-11ee-bb29-7af6acbff8ed",
			args: args{

				req2: utils.Empty[string](),

				req1: []string{utils.Empty[string]()},
			},
			wantErr: false,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			defer func() {
				//统一处理
				if err := recover(); err != nil {
					t.Log("recover了")
				}
			}()

			RequestEllipsis(tt.args.req2, tt.args.req1...)

		})
	}
}
