// Code generated by codeParser. DO NOT EDIT.
// Code generated by codeParser. DO NOT EDIT.
// Code generated by codeParser. DO NOT EDIT.

package example

import (
	"slp/reconcile/core/common/utils"
	"testing"
)

func Test_requestRequestStruct(t *testing.T) {
	type fields struct {
	}
	type args struct {
		req1 Example
	}
	tests := []struct {
		args    args
		name    string
		fields  fields
		wantErr bool
	}{
		{
			name: "15423b80-f59d-11ee-af52-7af6acbff8ed",
			args: args{

				req1: utils.Empty[Example](),
			},
			wantErr: false,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			defer func() {
				//统一处理
				if err := recover(); err != nil {
					t.Log("recover了")
				}
			}()

			RequestStruct(tt.args.req1)

		})
	}
}
