// Code generated by codeParser. DO NOT EDIT.
// Code generated by codeParser. DO NOT EDIT.
// Code generated by codeParser. DO NOT EDIT.

package example

import (
	"testing"
)

func Test_requestRequestFunc(t *testing.T) {
	type fields struct {
	}
	type args struct {
		req1 func()
	}
	tests := []struct {
		args    args
		name    string
		fields  fields
		wantErr bool
	}{
		{
			name: "132a70d4-f5a1-11ee-bb29-7af6acbff8ed",
			args: args{

				req1: nil,
			},
			wantErr: false,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			defer func() {
				//统一处理
				if err := recover(); err != nil {
					t.Log("recover了")
				}
			}()

			RequestFunc(tt.args.req1)

		})
	}
}
