// Code generated by codeParser. DO NOT EDIT.
// Code generated by codeParser. DO NOT EDIT.
// Code generated by codeParser. DO NOT EDIT.

package example

import (
	"caseGenerator/utils"
	"testing"
)

func Test_requestRequestGeneric(t *testing.T) {
	type fields struct {
	}
	type args struct {
		list []T

		process func([]T) []R

		batchSize int
	}
	tests := []struct {
		args    args
		name    string
		fields  fields
		wantErr bool
	}{
		{
			name: "9c09cc56-f67d-11ee-bd7e-7af6acbff8ec",
			args: args{

				list: make([]T, 0, 10),

				process: nil,

				batchSize: utils.Empty[int](),
			},
			wantErr: false,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			defer func() {
				//统一处理
				if err := recover(); err != nil {
					t.Log("recover了")
				}
			}()

			RequestGeneric(tt.args.list, tt.args.process, tt.args.batchSize)

		})
	}
}
