// Code generated by codeParser. DO NOT EDIT.
// Code generated by codeParser. DO NOT EDIT.
// Code generated by codeParser. DO NOT EDIT.

package example

import (
	"caseGenerator/utils"
	"testing"
)

func Test_requestRequestVariableParam(t *testing.T) {
	type fields struct {
	}
	type args struct {
		req1 string
	}
	tests := []struct {
		args    args
		name    string
		fields  fields
		wantErr bool
	}{
		{
			name: "9c099268-f67d-11ee-bd7e-7af6acbff8ec",
			args: args{

				req1: utils.Empty[string](),
			},
			wantErr: false,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			defer func() {
				//统一处理
				if err := recover(); err != nil {
					t.Log("recover了")
				}
			}()

			RequestVariableParam(tt.args.req1)

		})
	}
}
