// Code generated by codeParser. DO NOT EDIT.
// Code generated by codeParser. DO NOT EDIT.
// Code generated by codeParser. DO NOT EDIT.

package example

import (
	"testing"
)

func Test_request_problemRequestResponseGenericValueProblem(t *testing.T) {
	type fields struct {
	}
	type args struct {
		param0 func() (*bool, bool)
	}
	tests := []struct {
		args    args
		name    string
		fields  fields
		wantErr bool
	}{
		{
			name: "a67f8524-03b9-11ef-a8b4-7af6acbff8ed",
			args: args{

				param0: nil,
			},
			wantErr: false,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			defer func() {
				//统一处理
				if err := recover(); err != nil {
					t.Log("recover了")
				}
			}()

			RequestResponseGenericValueProblem(tt.args.param0)

		})
	}
}
