// Code generated by codeParser. DO NOT EDIT.
// Code generated by codeParser. DO NOT EDIT.
// Code generated by codeParser. DO NOT EDIT.

package assignment

import (
	"caseGenerator/utils"
	"testing"
)

func Test_constConstAssignmentTest1(t *testing.T) {
	type fields struct {
	}
	type args struct {
	}
	tests := []struct {
		args    args
		name    string
		fields  fields
		wantErr bool
	}{
		{
			name:    "ConstAssignmentTest1",
			args:    args{},
			wantErr: false,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			defer func() {
				//统一处理
				if err := recover(); err != nil {
					t.Log("recover了")
				}
			}()

			ConstAssignmentTest1()

		})
	}
}

func Test_constConstAssignmentTest2(t *testing.T) {
	type fields struct {
	}
	type args struct {
		str string
	}
	tests := []struct {
		args    args
		name    string
		fields  fields
		wantErr bool
	}{
		{
			name: "ConstAssignmentTest2",
			args: args{

				str: utils.Empty[string](),
			},
			wantErr: false,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			defer func() {
				//统一处理
				if err := recover(); err != nil {
					t.Log("recover了")
				}
			}()

			ConstAssignmentTest2(tt.args.str)

		})
	}
}
